"""
AERIS — Enhanced Task Plan Model
Supports: step dependencies, context passing between steps, timing, and rich metadata.
"""
from __future__ import annotations

from typing import List, Dict, Any, Optional
from core.engine.state_manager import ExecutionStatus
import time


class TaskStep:
    """A single executable step within a task plan."""

    def __init__(
        self,
        step_id: str,
        description: str,
        tool_name: Optional[str] = None,
        tool_params: Optional[Dict[str, Any]] = None,
        depends_on: Optional[str] = None,
    ):
        self.step_id = step_id
        self.description = description
        self.tool_name = tool_name
        self.tool_params = tool_params or {}
        self.depends_on = depends_on  # step_id of prerequisite step
        self.status = ExecutionStatus.PENDING
        self.result: Any = None
        self.error: Optional[str] = None
        self.retry_count: int = 0
        self.started_at: Optional[float] = None
        self.finished_at: Optional[float] = None

    def mark_started(self):
        self.status = ExecutionStatus.RUNNING
        self.started_at = time.time()

    def mark_success(self, result: Any = None):
        self.status = ExecutionStatus.SUCCESS
        self.result = result
        self.finished_at = time.time()

    def mark_failed(self, error: str):
        self.status = ExecutionStatus.FAILED
        self.error = error
        self.finished_at = time.time()

    @property
    def duration_ms(self) -> Optional[float]:
        if self.started_at and self.finished_at:
            return round((self.finished_at - self.started_at) * 1000, 1)
        return None

    def to_dict(self):
        return {
            "step_id": self.step_id,
            "description": self.description,
            "tool_name": self.tool_name,
            "tool_params": self.tool_params,
            "depends_on": self.depends_on,
            "status": self.status,
            "result": str(self.result)[:500] if self.result else None,
            "error": self.error,
            "retry_count": self.retry_count,
            "duration_ms": self.duration_ms,
        }


class TaskPlan:
    """Represents a full multi-step plan generated by the Planner Agent."""

    def __init__(self, objective: str):
        self.objective = objective
        self.steps: List[TaskStep] = []
        self.current_step_index = 0
        self.created_at = time.time()
        # Context that flows between steps (e.g., previous step output feeds next step input)
        self.shared_context: Dict[str, Any] = {}

    def add_step(self, step: TaskStep):
        self.steps.append(step)

    def get_current_step(self) -> Optional[TaskStep]:
        if self.current_step_index < len(self.steps):
            return self.steps[self.current_step_index]
        return None

    def advance_step(self):
        self.current_step_index += 1

    def is_complete(self) -> bool:
        return self.current_step_index >= len(self.steps)

    def is_successful(self) -> bool:
        return self.is_complete() and all(
            step.status == ExecutionStatus.SUCCESS for step in self.steps
        )

    def get_completed_results(self) -> Dict[str, Any]:
        """Get all completed step results for context injection."""
        results = {}
        for step in self.steps:
            if step.status == ExecutionStatus.SUCCESS and step.result is not None:
                results[step.step_id] = {
                    "description": step.description,
                    "tool": step.tool_name,
                    "result": step.result,
                }
        return results

    # Parameters that should receive a cleaned file path instead of raw output
    _PATH_PARAMS = frozenset({
        "path", "file_path", "filepath", "input_path", "output_path",
        "directory", "dirpath", "search_dir", "filename",
    })

    def inject_previous_results(self, step: TaskStep):
        """Inject results from previous steps into current step params.
        If a param value is 'auto' or '$prev', replace with last step's result.
        For path-like parameters, extracts the first valid filepath from the
        previous output instead of dumping the entire raw string."""
        if not self.steps:
            return
        prev_results = self.get_completed_results()
        for key, value in list(step.tool_params.items()):
            if isinstance(value, str) and value in ("auto", "$prev", "$previous"):
                # Use the most recent successful step's result
                completed = [s for s in self.steps if s.status == ExecutionStatus.SUCCESS]
                if completed:
                    raw = str(completed[-1].result)
                    # For path-like parameters, extract just the first path
                    if key in self._PATH_PARAMS:
                        extracted = self._extract_first_path(raw)
                        step.tool_params[key] = extracted if extracted else raw[:500]
                    else:
                        step.tool_params[key] = raw[:2000]

    @staticmethod
    def _extract_first_path(text: str) -> str:
        """Extract the first file-system path from a block of text."""
        import re
        for line in text.strip().splitlines():
            line = line.strip()
            # Skip empty lines and obvious non-path lines
            if not line or line.startswith("[") or line.startswith("Contents of"):
                continue
            # Windows absolute path  (C:\..., D:\...)
            if re.match(r'^[A-Za-z]:[\\\/]', line):
                return line
            # Unix absolute path (/home/..., /Users/...)
            if line.startswith("/"):
                return line
            # Home-relative path
            if line.startswith("~"):
                return line
        # Fallback: return the first line that looks like it could be a path
        first_line = text.strip().splitlines()[0].strip() if text.strip() else ""
        return first_line

    def to_dict(self) -> Dict[str, Any]:
        return {
            "objective": self.objective,
            "steps": [s.to_dict() for s in self.steps],
            "current_step_index": self.current_step_index,
            "is_complete": self.is_complete(),
            "is_successful": self.is_successful(),
            "shared_context": {k: str(v)[:200] for k, v in self.shared_context.items()},
        }
