"""
AERIS — Proactive Intelligence Agent
Background cron-style workers that DON'T wait for user commands.
They run on schedule and proactively surface relevant information.

Features:
  - Morning Briefing (weather, calendar, news digest)
  - System Health Monitor (disk space, CPU, memory warnings)
  - Smart File Watcher (detect new downloads, suggest organization)
  - Periodic Memory Consolidation (compress chat history into facts)
"""
from __future__ import annotations

import logging
import platform
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger("AerisProactiveAgent")


@dataclass
class ProactiveAlert:
    """A proactive notification/insight generated by the agent."""
    alert_type: str  # "briefing", "health", "suggestion", "reminder"
    title: str
    message: str
    priority: str = "normal"  # "low", "normal", "high", "critical"
    timestamp: str = ""
    data: Dict[str, Any] = field(default_factory=dict)
    seen: bool = False

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now().isoformat()

    def to_dict(self) -> dict:
        return {
            "alert_type": self.alert_type,
            "title": self.title,
            "message": self.message,
            "priority": self.priority,
            "timestamp": self.timestamp,
            "data": self.data,
            "seen": self.seen,
        }


@dataclass
class ScheduledJob:
    """A recurring background job."""
    name: str
    func: Callable
    interval_seconds: int
    last_run: Optional[datetime] = None
    enabled: bool = True
    run_count: int = 0

    def is_due(self) -> bool:
        if not self.enabled:
            return False
        if self.last_run is None:
            return True
        return (datetime.now() - self.last_run).total_seconds() >= self.interval_seconds


from agents.base_agent import BaseAgent

class ProactiveAgent(BaseAgent):
    """
    Background intelligence agent.
    Runs periodic jobs and surfaces insights proactively.
    """

    MAX_ALERTS = 100

    def __init__(self):
        super().__init__(
            name="ProactiveAgent",
            description="Runs periodic background jobs and surfaces insights proactively.",
            task_domain="background",
            version="1.0.0",
            capabilities=[
                "System Health Monitoring",
                "Periodic Job Execution",
                "Background Task Scheduling",
                "Proactive Insights",
            ],
        )
        self._alerts: List[ProactiveAlert] = []
        self._jobs: Dict[str, ScheduledJob] = {}
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._lock = threading.Lock()
        
        # Smart caching & context
        self._cached_states: Dict[str, Any] = {}
        self._user_context = {"domain": "development", "is_busy": False}
        self._last_active_time = time.time()

        # Register built-in jobs
        self._register_builtin_jobs()

    # ── BaseAgent Abstract Methods ─────────────────────────────────────────────

    async def think(self, message: str, context: dict) -> Any:
        return message

    async def execute(self, plan: Any) -> Any:
        return plan

    async def report(self, results: Any) -> str:
        return str(results)

    # ═════════════════════════════════════════════════════════════════
    #  JOB MANAGEMENT
    # ═════════════════════════════════════════════════════════════════

    def _register_builtin_jobs(self):
        """Register all default proactive jobs."""
        self.register_job("system_health", self._job_system_health, interval_seconds=600)
        self.register_job("download_watcher", self._job_download_watcher, interval_seconds=120)
        self.register_job("memory_consolidation", self._job_memory_consolidation, interval_seconds=1800)
        self.register_job("disk_space_check", self._job_disk_space, interval_seconds=900)
        self.register_job("context_awareness", self._job_context_awareness, interval_seconds=60)
        self.register_job("presence_ping", self._job_presence_ping, interval_seconds=90)
        self.register_job("integrity_check", self._job_integrity_check, interval_seconds=7200)
        self.register_job("critical_domain_monitor", self._job_critical_domain_monitor, interval_seconds=3600)
        self.register_job("proactive_news", self._job_proactive_news, interval_seconds=1800)

    def register_job(self, name: str, func: Callable, interval_seconds: int):
        """Register a new periodic job."""
        self._jobs[name] = ScheduledJob(name=name, func=func, interval_seconds=interval_seconds)

    def enable_job(self, name: str) -> bool:
        if name in self._jobs:
            self._jobs[name].enabled = True
            return True
        return False

    def disable_job(self, name: str) -> bool:
        if name in self._jobs:
            self._jobs[name].enabled = False
            return True
        return False

    # ═════════════════════════════════════════════════════════════════
    #  LIFECYCLE
    # ═════════════════════════════════════════════════════════════════

    def start(self):
        """Start the proactive agent background loop."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()
        logger.info("ProactiveAgent started")

    def stop(self):
        """Stop the proactive agent."""
        self._running = False
        logger.info("ProactiveAgent stopped")

    def _run_loop(self):
        """Main background loop — checks all jobs periodically with dynamic frequency."""
        while self._running:
            # Dynamic interval adjustment based on user context
            multiplier = 1.0
            if self._user_context.get("is_busy"):
                multiplier = 2.0  # Slow down background tasks if busy
            elif time.time() - self._last_active_time > 3600:
                multiplier = 0.5  # Give more resources to sensing if idle

            for name, job in self._jobs.items():
                # Check if job is due, considering the dynamic multiplier
                is_due = False
                if job.enabled:
                    if job.last_run is None:
                        is_due = True
                    else:
                        is_due = (datetime.now() - job.last_run).total_seconds() >= (job.interval_seconds * multiplier)

                if is_due:
                    try:
                        from engine.state_manager import global_state_manager
                        job_action_mapping = {
                            "system_health": "Sir, system monitor kar raha hoon...",
                            "download_watcher": "Sir, downloads check kar raha hoon...",
                            "critical_domain_monitor": "Sir, virus aur threats scan kar raha hoon...",
                            "integrity_check": "Sir, system files check kar raha hoon...",
                            "proactive_news": "Sir, latest updates check kar raha hoon..."
                        }
                        if name in job_action_mapping:
                            global_state_manager.set_global_action(job_action_mapping[name])
                    except Exception:
                        pass

                    try:
                        job.func()
                        job.last_run = datetime.now()
                        job.run_count += 1
                    except Exception as e:
                        logger.error(f"Proactive job '{name}' failed: {e}")
            
            try:
                from engine.state_manager import global_state_manager
                # Clear status only if we just ran a background task
                bg_statuses = [
                    "Sir, system monitor kar raha hoon...", 
                    "Sir, downloads check kar raha hoon...", 
                    "Sir, virus aur threats scan kar raha hoon...", 
                    "Sir, system files check kar raha hoon...",
                    "Sir, latest updates check kar raha hoon..."
                ]
                if global_state_manager.global_current_action in bg_statuses:
                    global_state_manager.set_global_action("Idle")
            except Exception:
                pass
            time.sleep(10)  # Poll every 10 seconds

    # ═════════════════════════════════════════════════════════════════
    #  ALERTS
    # ═════════════════════════════════════════════════════════════════

    def _add_alert(self, alert: ProactiveAlert):
        """Thread-safe alert addition. Uses Smart Interruption Logic."""
        # Smart Interruption Logic: skip or delay low priority if busy
        if self._user_context.get("is_busy") and alert.priority in ("low", "normal"):
            logger.info(f"Skipping or delaying non-urgent alert (user is busy): {alert.title}")
            # Optionally cache to deliver later. For now, silent default to prevent spam.
            if alert.priority == "low":
                return
            else:
                alert.priority = "delayed_normal"
        
        # Debounce/Cache check to avoid redundant alerts
        cache_key = f"{alert.alert_type}_{alert.title}"
        last_alert_time = self._cached_states.get(cache_key)
        if last_alert_time and (datetime.now() - last_alert_time).total_seconds() < 3600 * 4:
            # Found same alert in the past 4 hours.
            if alert.priority != "critical":
                return # Skip redundant repeated alert, keep it quiet
                
        self._cached_states[cache_key] = datetime.now()

        with self._lock:
            self._alerts.append(alert)
            if len(self._alerts) > self.MAX_ALERTS:
                self._alerts = self._alerts[-self.MAX_ALERTS:]

    def get_alerts(self, unseen_only: bool = False) -> List[Dict]:
        """Get all alerts, optionally only unseen ones."""
        with self._lock:
            alerts = self._alerts
            if unseen_only:
                alerts = [a for a in alerts if not a.seen]
            return [a.to_dict() for a in alerts]

    def mark_seen(self, index: int = -1):
        """Mark alerts as seen. -1 = mark all."""
        with self._lock:
            if index == -1:
                for a in self._alerts:
                    a.seen = True
            elif 0 <= index < len(self._alerts):
                self._alerts[index].seen = True

    def get_unseen_count(self) -> int:
        with self._lock:
            return sum(1 for a in self._alerts if not a.seen)

    # ═════════════════════════════════════════════════════════════════
    #  BUILT-IN JOBS
    # ═════════════════════════════════════════════════════════════════

    def _job_system_health(self):
        """Check system health: CPU, memory, battery."""
        try:
            import psutil
            cpu_percent = psutil.cpu_percent(interval=2)
            memory = psutil.virtual_memory()
            mem_percent = memory.percent

            # Debounce rapid reporting
            prev_cpu = self._cached_states.get("prev_cpu", 0)
            if abs(cpu_percent - prev_cpu) < 10 and cpu_percent < 90:
                self._cached_states["prev_cpu"] = cpu_percent
                return
            self._cached_states["prev_cpu"] = cpu_percent

            alerts = []
            if cpu_percent > 90:
                alerts.append(f"CPU is high ({cpu_percent}%).")
            if mem_percent > 90:
                alerts.append(f"Memory is critical ({mem_percent}%).")

            # Battery check
            try:
                battery = psutil.sensors_battery()
                if battery and not battery.power_plugged and battery.percent < 20:
                    alerts.append(f"🔋 Battery low: **{battery.percent}%** — plug in soon!")
            except Exception:
                pass

            if alerts:
                self._add_alert(ProactiveAlert(
                    alert_type="health",
                    title="System Health",
                    message=" ".join(alerts) + " Want details?",
                    priority="high" if mem_percent > 90 or cpu_percent > 90 else "normal",
                    data={"cpu": cpu_percent, "memory": mem_percent},
                ))

        except ImportError:
            pass  # psutil not available
        except Exception as e:
            logger.error(f"Health check failed: {e}")

    def _job_disk_space(self):
        """Check disk space and warn if low."""
        try:
            import shutil
            if platform.system() == "Windows":
                drives = ["C:\\", "D:\\"]
            else:
                drives = ["/"]

            for drive in drives:
                try:
                    total, used, free = shutil.disk_usage(drive)
                    free_gb = free / (1024 ** 3)
                    used_pct = (used / total) * 100

                    if free_gb < 10:
                        prev_free = self._cached_states.get(f"disk_{drive}", 100)
                        if abs(prev_free - free_gb) < 1:
                            continue # Hasn't meaningfully changed
                        self._cached_states[f"disk_{drive}"] = free_gb

                        self._add_alert(ProactiveAlert(
                            alert_type="health",
                            title="Low Disk Space",
                            message=f"Only {free_gb:.1f}GB free on {drive}. Clean up?",
                            priority="high" if free_gb < 5 else "normal",
                            data={"drive": drive, "free_gb": round(free_gb, 1), "used_pct": round(used_pct, 1)},
                        ))
                except Exception:
                    pass
        except Exception as e:
            logger.error(f"Disk space check failed: {e}")

    def _job_download_watcher(self):
        """Watch Downloads folder for new files and suggest organization."""
        try:
            downloads_dir = Path.home() / "Downloads"
            if not downloads_dir.exists():
                return

            # Count unorganized files (top-level only)
            files = [f for f in downloads_dir.iterdir() if f.is_file() and not f.name.startswith(".")]

            if len(files) > 20:
                file_count = len(files)
                prev_count = self._cached_states.get("downloads_count", 0)
                if abs(file_count - prev_count) < 5:
                    return # Avoid redundant alerts
                self._cached_states["downloads_count"] = file_count
                
                recent = sorted(files, key=lambda f: f.stat().st_mtime, reverse=True)[:5]
                recent_names = [f.name for f in recent]

                self._add_alert(ProactiveAlert(
                    alert_type="suggestion",
                    title="Downloads Activity",
                    message=f"Downloads folder has {file_count} items. Organize them?",
                    priority="low",
                    data={"file_count": file_count, "recent": recent_names},
                ))

        except Exception as e:
            logger.error(f"Download watcher failed: {e}")

    def _job_memory_consolidation(self):
        """Consolidate chat history into compressed long-term facts."""
        try:
            from services.chat_engine import _load_chat_log
            messages = _load_chat_log()

            if len(messages) < 30:
                return  # Not enough history to consolidate

            # Extract key facts from recent conversations
            user_messages = [m["content"] for m in messages if m.get("role") == "user"][-20:]
            if not user_messages:
                return

            # Find patterns: frequently mentioned topics, apps, files
            from collections import Counter
            all_words = " ".join(user_messages).lower().split()
            # Filter out common words
            stop = {"the", "a", "an", "is", "are", "was", "were", "and", "or", "but", "in", "on",
                    "at", "to", "for", "of", "with", "what", "how", "why", "when", "where", "can",
                    "do", "does", "did", "i", "you", "me", "my", "your", "it", "this", "that",
                    "please", "thanks", "hi", "hello", "hey"}
            meaningful = [w for w in all_words if len(w) > 2 and w not in stop]
            top_topics = Counter(meaningful).most_common(10)

            if top_topics:
                # Compare cache to avoid repeating exact same insight
                topic_keys = tuple(sorted([t[0] for t in top_topics[:3]]))
                if self._cached_states.get("last_topics") == topic_keys:
                    return
                self._cached_states["last_topics"] = topic_keys

                topics_str = ", ".join(f"{word}" for word, count in top_topics[:3])
                self._add_alert(ProactiveAlert(
                    alert_type="briefing",
                    title="Memory Insight",
                    message=f"Detected pattern: frequent focus on {topics_str}. Want a summary?",
                    priority="low",
                    data={"top_topics": dict(top_topics)},
                ))

        except Exception as e:
            logger.error(f"Memory consolidation failed: {e}")

    def _job_context_awareness(self):
        """Analyzes active usage patterns to adjust intelligent states."""
        try:
            import psutil
            is_busy = False
            # Rough proxy for "user is busy": high CPU user process running or code editors open
            busy_processes = ["code", "idea", "studio", "zoom", "teams", "devenv", "node", "npm", "python"]
            for proc in psutil.process_iter(['name', 'cpu_percent']):
                try:
                    name = proc.info['name'].lower() if proc.info['name'] else ""
                    if any(b in name for b in busy_processes) and proc.info['cpu_percent'] > 5.0:
                        is_busy = True
                        break
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    pass
            
            if is_busy:
                self._last_active_time = time.time()
                self._user_context["is_busy"] = True
            else:
                # Idle if 10 mins passed since last busy state
                if time.time() - self._last_active_time > 600:
                    self._user_context["is_busy"] = False
        except Exception:
            self._user_context["is_busy"] = False

    def _job_critical_domain_monitor(self):
        """Simulate scanning critical domains based on context (e.g., dev/cybersecurity)."""
        # A lightweight example of event-driven scanning
        domain = self._user_context.get("domain", "development")
        
        if domain not in ["development", "cybersecurity"]:
            return
            
        try:
            import requests
            # Use public CIRCL CVE feed to get the latest CVEs
            response = requests.get("https://cve.circl.lu/api/last", timeout=10)
            if response.status_code == 200:
                cves = response.json()
                for cve in cves:
                    # Filter for only high-impact (cvss > 7.0 or marked critical)
                    cvss = cve.get('cvss', 0)
                    if cvss and float(cvss) >= 7.0:
                        cve_id = cve.get('id', 'Unknown CVE')
                        summary = cve.get('summary', '')[:100]
                        cache_key = f"cve_{cve_id}"
                        
                        if not self._cached_states.get(cache_key):
                            self._cached_states[cache_key] = True
                            self._add_alert(ProactiveAlert(
                                alert_type="suggestion",
                                title="Security Update",
                                message=f"Critical vulnerability detected ({cve_id}): {summary}... Want details?",
                                priority="high"
                            ))
                            break # Only alert once per run to avoid spam
        except Exception as e:
            logger.error(f"Failed to fetch CVE feed: {e}")

    def _job_presence_ping(self):
        """Maintains continuous AI presence with memory-aware suggestions."""
        if self._user_context.get("is_busy") or self._user_context.get("is_muted"):
            return
            
        idle_time = time.time() - self._last_active_time
        if idle_time >= 180:  # 3 minutes
            import random
            
            # Base messages (always available)
            messages = [
                "Sir, systems are fully operational. Kuch help chahiye?",
                "Sir, background monitoring active hai. Standby par hoon.",
                "Sir, sab theek chal raha hai. Aapko meri zaroorat hai?",
                "Sir, main idhar hi hoon. Next command bataiye.",
            ]
            
            # Memory-aware messages: read long-term memory for follow-up suggestions
            try:
                import json
                from pathlib import Path
                mem_path = Path(__file__).parent / "data" / "memory" / "long_term.json"
                if mem_path.exists():
                    memory = json.loads(mem_path.read_text(encoding="utf-8"))
                    skip = {"hello", "hi", "hey", "stop", "ok", "okay", "haan", "yes", "no"}
                    recent_tasks = []
                    for entry in reversed(memory):
                        fact = entry.get("fact", "").replace("Successfully executed: ", "").strip()
                        if len(fact) > 8 and fact.lower() not in skip:
                            recent_tasks.append(fact)
                        if len(recent_tasks) >= 3:
                            break
                    
                    if recent_tasks:
                        task = random.choice(recent_tasks)
                        memory_msgs = [
                            f"Sir, aapne thodi der pehle '{task}' par kaam kiya tha. Continue karein?",
                            f"Sir, is '{task}' wale task mein koi aur update chahiye?",
                            f"Sir, '{task}' ke regarding koi aur details?",
                        ]
                        messages.extend(memory_msgs)
            except Exception:
                pass
            
            last_ping = self._cached_states.get("last_ping_time", 0)
            ping_interval = self._cached_states.get("next_ping_interval", 180)
            
            if time.time() - last_ping > ping_interval:
                self._cached_states["last_ping_time"] = time.time()
                self._cached_states["next_ping_interval"] = random.randint(180, 300)
                
                msg = random.choice(messages)
                self._add_alert(ProactiveAlert(
                    alert_type="briefing",
                    title="Presence Dot",
                    message=msg,
                    priority="normal"
                ))
                
               

    def _job_proactive_news(self):
        """Proactively fetch and share 1-2 important news updates when user is idle."""
        if self._user_context.get("is_busy") or self._user_context.get("is_muted"):
            return
        
        idle_time = time.time() - self._last_active_time
        if idle_time < 120:
            return  # Only share news if user is idle for at least 2 minutes
        
        # Anti-spam: only share once per 30 minutes
        last_news_time = self._cached_states.get("last_news_time", 0)
        if time.time() - last_news_time < 1800:
            return
            
        results_titles = []
        import random
        
        try:
            from googlesearch import search
            
            topics = [
                "latest cybersecurity news today",
                "latest AI technology news today",
                "latest tech updates today",
            ]
            domain = self._user_context.get("domain", "development")
            if domain == "cybersecurity":
                topics = ["latest cybersecurity vulnerability news today", "latest hacking news today"]
            
            query = random.choice(topics)
            # Try Google Search first
            raw_results = list(search(query, advanced=True, num_results=3))
            
            for r in raw_results:
                results_titles.append(r.title)
                
        except Exception as e:
            logger.warning(f"Google Search failed (likely 429). Falling back to Hacker News: {e}")
            try:
                import requests
                # Fallback to Hacker News API
                resp = requests.get("https://hacker-news.firebaseio.com/v0/topstories.json", timeout=10)
                if resp.status_code == 200:
                    top_ids = resp.json()[:15]
                    random.shuffle(top_ids)
                    
                    for item_id in top_ids:
                        item_resp = requests.get(f"https://hacker-news.firebaseio.com/v0/item/{item_id}.json", timeout=5)
                        if item_resp.status_code == 200:
                            data = item_resp.json()
                            if data and "title" in data:
                                results_titles.append(data["title"])
                        if len(results_titles) >= 3:
                            break
            except Exception as e2:
                logger.error(f"Fallback news fetch also failed: {e2}")
                return

        if results_titles:
            shared_titles = self._cached_states.get("shared_news_titles", set())
            new_results = [t for t in results_titles if t not in shared_titles]
            
            if not new_results:
                return
                
            picked = new_results[:2]
            bullets = []
            for t in picked:
                bullets.append(f"• {t}")
                shared_titles.add(t)
                
            self._cached_states["shared_news_titles"] = shared_titles
            self._cached_states["last_news_time"] = time.time()
            
            news_text = "Latest tech headlines check kiye the:\n" + "\n".join(bullets)
            
            self._add_alert(ProactiveAlert(
                alert_type="briefing",
                title="Proactive News",
                message=news_text,
                priority="normal"
            ))

    def _job_integrity_check(self):
        """Self-monitoring system integrity check to locate dead files or broken connections."""
        try:
            import ast
            import pathlib
            
            backend_dir = pathlib.Path(__file__).parent
            py_files = list(backend_dir.glob("*.py"))
            
            module_imports = set()
            for pf in py_files:
                try:
                    tree = ast.parse(pf.read_text(encoding="utf-8"))
                    for node in ast.walk(tree):
                        if isinstance(node, ast.Import):
                            for n in node.names:
                                module_imports.add(n.name)
                        elif isinstance(node, ast.ImportFrom):
                            if node.module:
                                module_imports.add(node.module)
                except Exception:
                    pass
                    
            dead_modules = []
            for pf in py_files:
                stem = pf.stem
                if stem not in module_imports and stem not in ["api", "run", "setup", "__init__"]:
                    dead_modules.append(stem)
                    
            try:
                # Integrate with tools.py & core module registries to detect unregistered tools
                from tools.universal_registry import get_universal_registry
                from tools import tool_names
                reg_names = set(get_universal_registry().get_tool_names())
                t_names = set(tool_names())
                unregistered = t_names - reg_names
                for u in unregistered:
                    dead_modules.append(f"Unregistered Tool ({u})")
            except Exception:
                pass
                    
            if dead_modules:
                cache_key = f"dead_modules_{len(dead_modules)}"
                if not self._cached_states.get(cache_key):
                    self._cached_states[cache_key] = True
                    self._add_alert(ProactiveAlert(
                        alert_type="health",
                        title="Integrity Warning",
                        message=f"Detected system issues (unused files/unregistered tools): {', '.join(dead_modules[:3])}. Suggest fix or removal?",
                        priority="normal"
                    ))
        except Exception as e:
            logger.error(f"Integrity check failed: {e}")

    # ═════════════════════════════════════════════════════════════════
    #  MORNING BRIEFING (on-demand or scheduled)
    # ═════════════════════════════════════════════════════════════════

    def generate_morning_briefing(self) -> str:
        """Generate a comprehensive morning briefing."""
        sections = []
        now = datetime.now()

        # Header
        sections.append(f"## ☀️ Good Morning! Here's your briefing for {now.strftime('%A, %B %d, %Y')}\n")

        # System Status
        try:
            import psutil
            cpu = psutil.cpu_percent(interval=1)
            mem = psutil.virtual_memory()
            sections.append("### 💻 System Status")
            sections.append(f"- CPU: {cpu}% | RAM: {mem.percent}% ({mem.used // (1024**3)}GB / {mem.total // (1024**3)}GB)")
            try:
                battery = psutil.sensors_battery()
                if battery:
                    plug = "🔌 Plugged in" if battery.power_plugged else "🔋 On battery"
                    sections.append(f"- Battery: {battery.percent}% ({plug})")
            except Exception:
                pass
        except ImportError:
            sections.append("### 💻 System Status\n- *Install `psutil` for system monitoring*")

        # Disk Space
        try:
            import shutil
            total, used, free = shutil.disk_usage("C:\\" if platform.system() == "Windows" else "/")
            sections.append(f"- Disk: {free / (1024**3):.1f}GB free / {total / (1024**3):.0f}GB total")
        except Exception:
            pass

        # Downloads count
        try:
            dl = Path.home() / "Downloads"
            if dl.exists():
                count = sum(1 for f in dl.iterdir() if f.is_file())
                if count > 0:
                    sections.append(f"\n### 📥 Downloads\n- {count} files in Downloads folder")
        except Exception:
            pass

        # Pending alerts
        unseen = self.get_unseen_count()
        if unseen:
            sections.append(f"\n### 🔔 Notifications\n- {unseen} unseen alert(s)")

        sections.append(f"\n---\n*Generated at {now.strftime('%I:%M %p')}*")
        return "\n".join(sections)

    # ═════════════════════════════════════════════════════════════════
    #  STATUS
    # ═════════════════════════════════════════════════════════════════

    def get_status(self) -> Dict:
        return {
            "running": self._running,
            "jobs": {
                name: {
                    "enabled": job.enabled,
                    "interval_seconds": job.interval_seconds,
                    "last_run": job.last_run.isoformat() if job.last_run else None,
                    "run_count": job.run_count,
                    "is_due": job.is_due(),
                }
                for name, job in self._jobs.items()
            },
            "alert_count": len(self._alerts),
            "unseen_alerts": self.get_unseen_count(),
        }


# Global instance
_proactive_agent: Optional[ProactiveAgent] = None


def get_proactive_agent() -> ProactiveAgent:
    global _proactive_agent
    if _proactive_agent is None:
        _proactive_agent = ProactiveAgent()
    return _proactive_agent

# Module-level alias for direct import (used by api.py muting logic)
agent = get_proactive_agent()

if __name__ == "__main__":
    # Allow running this script directly for testing by adding the BACKEND dir to sys.path
    import sys
    from pathlib import Path
    backend_dir = Path(__file__).resolve().parent.parent
    if str(backend_dir) not in sys.path:
        sys.path.insert(0, str(backend_dir))
        
    logging.basicConfig(level=logging.INFO)
    print("Testing ProactiveAgent instantiation...")
    # Safe to import agents.base_agent now!
    agent_instance = get_proactive_agent()
    print(f"Agent '{agent_instance.name}' created successfully with {len(agent_instance._jobs)} registered jobs.")
